
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: asdf1234
      MARIADB_DATABASE: streamvaultapp
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=asdf1234" ]
  adminer:
    image: adminer
    restart: always
    ports:
      - "7070:8080"
    depends_on:
      db:
           condition: service_healthy
  backend:
    image: streamvault/backend
    restart: always
    build:
      context: ./streamvault-backend
    ports:
      - "8080:8080"
    depends_on:
     db:
           condition: service_healthy

  frontend:
    image: streamvault/frontend
    restart: always
    build:
      context: ./streamvault-frontend
      args:
        - STREAMVAULT_API=${STREAMVAULT_API}
    ports:
      - "80:80"
    depends_on:
       - backend
