name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ----------------- Backend -----------------
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build Backend and Run Tests
        working-directory: streamvault-backend
        run: mvn clean verify

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Backend Docker Image
        working-directory: streamvault-backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blogging-backend:latest .

      - name: Push Backend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/blogging-backend:latest

      # ----------------- Frontend / Nginx -----------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: streamvault-frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: streamvault-frontend
        run: npm install

      - name: Create production env file
        run: |
          echo "VITE_APP_STREAMVAULT_API=https://blog.bakwowi.dev/api" > streamvault-frontend/.env.production

      - name: Build React App
        working-directory: streamvault-frontend
        run: npm run build

      - name: Build Nginx Docker Image
        working-directory: streamvault-frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blogging-nginx:latest .

      - name: Push Nginx Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/blogging-nginx:latest
